using System.ComponentModel.DataAnnotations;

namespace GildeApp.Api.Dtos.Matches
{
    /// <summary>
    /// What the judge's mobile app posts. Matches are generated by the API, never
    /// created by hand, so this only carries the two scores.
    /// </summary>
    public class MatchScoreDto
    {
        [Range(0, 999)]
        public int FirstScore { get; set; }

        [Range(0, 999)]
        public int SecondScore { get; set; }

        /// <summary>
        /// False while the bout is still running, so the board shows a live score.
        /// True locks the result in.
        /// </summary>
        public bool Finish { get; set; }
    }
}
